export const demoLeads = [
  {
    id: "demo-1",
    name: "Maya Patel",
    email: "maya.patel@northlinehomes.com",
    company: "Northline Homes",
    property_address: "1200 Commerce St",
    city: "Austin",
    state: "TX",
    country: "US",
    status: "processing",
    created_at: "2026-04-24T18:10:00Z",
    enrichment: {
      identity_complete: true,
      company_complete: true,
      market_complete: true,
      property_complete: false,
      values_complete: true,
      scoring_complete: false,
      outreach_complete: false,
      identity_data: {
        verified_title: "VP of Operations",
        seniority: "executive",
        dm_probability: 0.78,
      },
      company_data: {
        company_size: "51-200",
        is_residential: true,
        is_real_estate: true,
      },
      market_data: {
        vacancy_trend: "tightening",
        rent_growth: "above metro median",
      },
      values_data: {
        signals: ["resident experience", "operations automation", "portfolio growth"],
      },
      score: null,
      tier: null,
      recommended_action: "Scoring is waiting on property enrichment.",
    },
  },
  {
    id: "demo-2",
    name: "Daniel Kim",
    email: "dkim@harborstonepm.com",
    company: "Harborstone Property Management",
    property_address: "88 Pier Avenue",
    city: "Long Beach",
    state: "CA",
    country: "US",
    status: "complete",
    created_at: "2026-04-23T15:24:00Z",
    completed_at: "2026-04-23T15:31:00Z",
    enrichment: {
      identity_complete: true,
      company_complete: true,
      market_complete: true,
      property_complete: true,
      values_complete: true,
      scoring_complete: true,
      outreach_complete: true,
      score: 86,
      tier: "hot",
      pitch_angle: "resident_experience_and_efficiency",
      recommended_action: "Prioritize SDR outreach today with an operations efficiency angle.",
      insights: [
        "Residential portfolio fit with active leasing operations.",
        "Market pressure suggests vacancy reduction has immediate value.",
        "Company hiring language points to process automation interest.",
        "Decision-maker probability is high based on role and seniority.",
        "Walkability and local amenities support resident-experience messaging.",
      ],
      talking_points: [
        "Reducing manual leasing follow-up across multiple properties.",
        "Improving resident response speed without adding headcount.",
        "Using market signals to prioritize high-intent prospects.",
      ],
      email_draft:
        "Hi Daniel,\n\nI noticed Harborstone is operating in a competitive Long Beach market where faster resident follow-up can materially affect leasing outcomes. LeadAI helps property teams identify high-intent residents and automate the next best outreach without adding operational load.\n\nWould it be worth comparing notes for 15 minutes next week?\n\nBest,\nLeadAI",
    },
  },
  {
    id: "demo-3",
    name: "Lena Morris",
    email: "lena@civicretailgroup.com",
    company: "Civic Retail Group",
    property_address: "305 Market Row",
    city: "Denver",
    state: "CO",
    country: "US",
    status: "complete",
    created_at: "2026-04-22T20:02:00Z",
    completed_at: "2026-04-22T20:08:00Z",
    enrichment: {
      identity_complete: true,
      company_complete: true,
      market_complete: true,
      property_complete: true,
      values_complete: true,
      scoring_complete: true,
      outreach_complete: false,
      score: 12,
      tier: "disqualified",
      recommended_action: "Do not contact. Company appears focused on retail, not residential real estate.",
      insights: ["Company does not match residential property management criteria."],
    },
  },
];

export const makeDemoLead = (payload) => ({
  id: `demo-${Date.now()}`,
  ...payload,
  status: "pending",
  created_at: new Date().toISOString(),
  enrichment: {
    identity_complete: false,
    company_complete: false,
    market_complete: false,
    property_complete: false,
    values_complete: false,
    scoring_complete: false,
    outreach_complete: false,
    recommended_action: "Queued for enrichment.",
  },
});
